# Generated by Django 6.0.2 on 2026-02-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_description_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='business_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postcode',
        ),
    ]
