# Generated by Django 6.0.2 on 2026-03-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_product_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('in_season', 'In Season (Available)'), ('year_round', 'Available Year-Round'), ('unavailable', 'Unavailable / Out of Season')], default='in_season', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('veg', 'Vegetables'), ('dairy_eggs', 'Dairy & Eggs'), ('bakery', 'Bakery'), ('preserves', 'Preserves'), ('seasonal', 'Seasonal Specialties')], default='veg', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='Each', max_length=50),
        ),
    ]
