# Generated by Django 6.0.2 on 2026-03-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_product_availability_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_community_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
