# Generated by Django 6.0.3 on 2026-04-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_order_special_instructions'),
        ('marketplace', '0010_product_low_stock_threshold_notification_review'),
    ]

    operations = [
    ]
