# Generated by Django 6.0.3 on 2026-04-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_merge_20260406_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_charity_or_education',
            field=models.BooleanField(default=False),
        ),
    ]
