# Generated by Django 6.0.3 on 2026-04-06 21:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_user_is_charity_or_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bulk_discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='invoice_payment_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
