# Generated by Django 6.0.3 on 2026-04-06 21:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_user_bulk_discount_rate_user_invoice_payment_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='bulk_discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percentage discount available for approved community group accounts.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='invoice_payment_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
