# Generated by Django 6.0.4 on 2026-05-06 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_food_miles_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(blank=True, default=0, help_text='Discount between 10% and 50%', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='product',
            name='is_surplus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='surplus_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='surplus_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
